version: '3.9'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gerenciador
      POSTGRES_HOST: localhost
    ports:
      - "5429:5432"
